# Generated by Django 5.0.6 on 2024-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
